apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
spec:
  replicas: 2
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
      - name: products
        image: registry.cloudemon.me/devops-620/products:latest
        resources:
          # Add this section
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8002
        envFrom:
        - configMapRef:
            name: product-config
