apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopping
  template:
    metadata:
      labels:
        app: shopping
    spec:
      containers:
      - name: shopping
        image: registry.cloudemon.me/devops-620/shopping:latest
        resources:
          # Add this section
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8003
        envFrom:
        - configMapRef:
            name: shopping-config
